spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: awan
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:mariadb://localhost:3306/pznrestapi"
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
